# Generated by Django 5.0.1 on 2025-05-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='tags',
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('Video', 'Video'), ('Ebook', 'Ebook')], max_length=10),
        ),
    ]
